
all:
	xml2rfc proposal.xml --basename=../draft --raw --text --html

text:
	xml2rfc proposal.xml -o ../draft.txt --raw

paginated:
	xml2rfc proposal.xml -o ../draft-paginated.txt --text

html:
	xml2rfc proposal.xml -o ../draft.html --html

